# Generated by Django 4.0.2 on 2022-06-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxilio',
            options={'permissions': (('aux', 'aux'),)},
        ),
    ]
