# Generated by Django 4.0.2 on 2022-06-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilio', '0003_auxilio_criado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxilio',
            options={'permissions': (('aux', 'aux'), ('atual', 'atual'), ('exc', 'exc'))},
        ),
    ]
