# Generated by Django 4.0.2 on 2022-07-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilio', '0004_alter_auxilio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxilio',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
