# Generated by Django 4.0.2 on 2022-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilio', '0005_auxilio_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxilio',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
