# Generated by Django 4.0.2 on 2022-06-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
