# Generated by Django 4.0.2 on 2022-06-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('perfil_user', 'perfil'),)},
        ),
        migrations.AlterModelOptions(
            name='serve',
            options={'permissions': (('add', 'add'), ('perfil_serve', 'perfil'))},
        ),
    ]
