# Generated by Django 4.0.2 on 2022-06-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_perfil_options_alter_serve_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('add', 'add'), ('perfil', 'perfil'))},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='turma',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='curso',
            field=models.CharField(choices=[['Info', 'Informática'], ['Agro_ind', 'Agroindrustria'], ['Agro', 'Agropecuaria'], ['Serv', 'servidor'], ['Super', 'superior']], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Serve',
        ),
    ]
