# Generated by Django 4.0.2 on 2022-07-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curso',
            field=models.CharField(choices=[['Info', 'Informática'], ['Agro_ind', 'Agroindrustria'], ['Agro', 'Agropecuaria'], ['N', 'nenhuma'], ['Super', 'superior']], max_length=10, null=True),
        ),
    ]
