# Generated by Django 4.0.2 on 2022-07-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
