# Generated by Django 4.0.2 on 2022-07-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='foto',
        ),
    ]
