# Generated by Django 4.0.2 on 2022-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0005_remove_post_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postar',
            field=models.BooleanField(default=False),
        ),
    ]
