# Generated by Django 4.0.2 on 2022-07-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
