# Generated by Django 4.0.2 on 2022-06-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estagio',
            options={'permissions': (('est', 'est'),)},
        ),
    ]
