# Generated by Django 4.0.2 on 2022-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='postar',
            field=models.BooleanField(default=False),
        ),
    ]
